### PR TITLE
Add scaleX and scaleY props

### PR DESCRIPTION
**Pull request by kybetter**
In few actual project, we need set both scaleX and scaleY props, not only one scale prop, so I add them.

### CODE REVIEW

**Comment by kybetter** [comment]
And fixed change* calculate bug.

**Comment by jrohland** [comment]
Having the separate props is great but more importantly this PR fixes the broken scale prop that was introduced in 2.2.0.

**Comment by mauricius** [comment]
Looks good @kybetter, but can't you modify the `scale` prop to support also an array of two elements instead of adding two more props? It would not change the behavior for existing users. And also we wouldn't have to deprecate it in the future. 

Thanks

**Comment by kybetter** [comment]
Thank you for your advice, I combined scaleX and scaleY to scale prop.

**Pull request merged**
